/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kiểm tra trạng thái API
         * @description Kiểm tra service backend và kết nối MySQL thông qua Prisma.
         */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh sách người dùng
         * @description Lấy danh sách người dùng summary kèm vai trò ngắn gọn. Hỗ trợ tìm theo họ tên, email hoặc số điện thoại. Yêu cầu permission USERS_READ.
         */
        get: operations["UsersController_findMany"];
        put?: never;
        /**
         * Tạo người dùng
         * @description Tạo tài khoản người dùng CMS hoặc khách hàng. BE tự hash password và gán roleIds nếu có. Yêu cầu permission USERS_CREATE.
         */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chi tiết người dùng
         * @description Lấy chi tiết người dùng kèm danh sách vai trò. Yêu cầu permission USERS_READ.
         */
        get: operations["UsersController_findById"];
        put?: never;
        post?: never;
        /**
         * Xóa người dùng
         * @description Xóa mềm người dùng bằng deletedAt và chuyển trạng thái sang INACTIVE.
         */
        delete: operations["UsersController_delete"];
        options?: never;
        head?: never;
        /**
         * Cập nhật người dùng
         * @description Cập nhật thông tin tài khoản, trạng thái, mật khẩu và danh sách vai trò. Mutate endpoint chỉ trả message.
         */
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng ký tài khoản khách hàng
         * @description Tạo user CUSTOMER mới bằng email hoặc số điện thoại, hash mật khẩu, gán role CUSTOMER và trả access token + refresh token.
         */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng nhập
         * @description Đăng nhập bằng email hoặc số điện thoại. Token chỉ chứa identity; quyền được check runtime từ DB.
         */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Làm mới token
         * @description Thu hồi refresh token cũ nếu còn hiệu lực và cấp cặp access token + refresh token mới.
         */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng xuất
         * @description Thu hồi refresh token hiện tại. Access token sẽ tự hết hạn theo TTL.
         */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lấy thông tin người dùng hiện tại
         * @description Đọc user từ Bearer access token và trả profile kèm roles/permissions hiện tại trong DB.
         */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh sách vai trò
         * @description Lấy danh sách role kèm permissions đang gán. Yêu cầu permission ROLES_READ.
         */
        get: operations["RolesController_findMany"];
        put?: never;
        /**
         * Tạo vai trò
         * @description Tạo role mới để gán cho user. Yêu cầu permission ROLES_CREATE theo DB runtime.
         */
        post: operations["RolesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chi tiết vai trò
         * @description Lấy chi tiết role theo id, bao gồm danh sách permissions.
         */
        get: operations["RolesController_findById"];
        put?: never;
        post?: never;
        /**
         * Vô hiệu hóa vai trò
         * @description Soft-deactivate role bằng cách chuyển status sang INACTIVE. Yêu cầu permission ROLES_DELETE.
         */
        delete: operations["RolesController_deactivate"];
        options?: never;
        head?: never;
        /**
         * Cập nhật vai trò
         * @description Cập nhật thông tin role. Yêu cầu permission ROLES_UPDATE.
         */
        patch: operations["RolesController_update"];
        trace?: never;
    };
    "/roles/{id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Gán quyền cho vai trò
         * @description Thay thế toàn bộ permissions hiện tại của role bằng danh sách permissionCodes. Có hiệu lực ngay ở request kế tiếp vì guard check DB runtime.
         */
        patch: operations["RolesController_syncPermissions"];
        trace?: never;
    };
    "/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh sách quyền
         * @description Lấy danh sách permissions, gồm code/module/action/method/path/status. Yêu cầu permission PERMISSIONS_READ.
         */
        get: operations["PermissionsController_findMany"];
        put?: never;
        /**
         * Tạo quyền
         * @description Tạo permission động. Nếu truyền method/path, guard có thể check quyền theo route runtime.
         */
        post: operations["PermissionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chi tiết quyền
         * @description Lấy chi tiết permission theo id.
         */
        get: operations["PermissionsController_findById"];
        put?: never;
        post?: never;
        /**
         * Vô hiệu hóa quyền
         * @description Chuyển permission sang INACTIVE. Request kế tiếp sẽ không còn pass guard theo quyền này.
         */
        delete: operations["PermissionsController_deactivate"];
        options?: never;
        head?: never;
        /**
         * Cập nhật quyền
         * @description Cập nhật permission, bao gồm method/path để đổi route policy runtime. Yêu cầu PERMISSIONS_UPDATE.
         */
        patch: operations["PermissionsController_update"];
        trace?: never;
    };
    "/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh sách ga
         * @description Lấy danh sách ga chưa bị xóa mềm, hỗ trợ tìm theo tên/code và lọc theo city/status. Yêu cầu permission STATIONS_READ.
         */
        get: operations["StationsController_findMany"];
        put?: never;
        /**
         * Tạo ga
         * @description Tạo ga tàu mới. Code phải viết hoa, không dấu, không khoảng trắng. Yêu cầu permission STATIONS_CREATE.
         */
        post: operations["StationsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chi tiết ga
         * @description Lấy chi tiết ga theo id, không trả bản ghi đã bị xóa mềm.
         */
        get: operations["StationsController_findById"];
        put?: never;
        post?: never;
        /**
         * Xóa mềm ga
         * @description Không hard delete. Endpoint chỉ cập nhật deletedAt = now. Yêu cầu permission STATIONS_DELETE.
         */
        delete: operations["StationsController_delete"];
        options?: never;
        head?: never;
        /**
         * Cập nhật ga
         * @description Cập nhật thông tin ga. Code vẫn phải viết hoa, không dấu, không khoảng trắng. Yêu cầu permission STATIONS_UPDATE.
         */
        patch: operations["StationsController_update"];
        trace?: never;
    };
    "/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh sách tuyến
         * @description Lấy danh sách tuyến chưa bị xóa mềm, hỗ trợ tìm theo tên/code và lọc theo status. Yêu cầu permission ROUTES_READ.
         */
        get: operations["RoutesController_findMany"];
        put?: never;
        /**
         * Tạo tuyến
         * @description Tạo tuyến mới kèm danh sách ga dừng. Yêu cầu ít nhất 2 ga, thứ tự ga và station không trùng, khoảng cách tăng dần. Yêu cầu permission ROUTES_CREATE.
         */
        post: operations["RoutesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chi tiết tuyến
         * @description Lấy chi tiết tuyến theo id kèm danh sách ga dừng, không trả bản ghi đã bị xóa mềm.
         */
        get: operations["RoutesController_findById"];
        put?: never;
        post?: never;
        /**
         * Xóa mềm tuyến
         * @description Không hard delete. Endpoint chỉ cập nhật deletedAt = now. Yêu cầu permission ROUTES_DELETE.
         */
        delete: operations["RoutesController_delete"];
        options?: never;
        head?: never;
        /**
         * Cập nhật tuyến
         * @description Cập nhật thông tin tuyến. Nếu gửi stops thì thay thế toàn bộ danh sách ga dừng hiện tại trong transaction. Yêu cầu permission ROUTES_UPDATE.
         */
        patch: operations["RoutesController_update"];
        trace?: never;
    };
    "/trains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh sách tàu
         * @description Lấy danh sách tàu chưa bị xóa mềm, không trả nested carriages/seats.
         */
        get: operations["TrainsController_findMany"];
        put?: never;
        /**
         * Tạo tàu
         * @description Tạo tàu vật lý mới. Yêu cầu permission TRAINS_CREATE.
         */
        post: operations["TrainsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trains/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chi tiết tàu
         * @description Lấy chi tiết tàu kèm danh sách toa summary.
         */
        get: operations["TrainsController_findById"];
        put?: never;
        post?: never;
        /**
         * Xóa mềm tàu
         * @description Không hard delete, chỉ cập nhật deletedAt. Yêu cầu TRAINS_DELETE.
         */
        delete: operations["TrainsController_delete"];
        options?: never;
        head?: never;
        /**
         * Cập nhật tàu
         * @description Cập nhật thông tin tàu. Yêu cầu permission TRAINS_UPDATE.
         */
        patch: operations["TrainsController_update"];
        trace?: never;
    };
    "/seat-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh sách loại ghế
         * @description Lấy danh sách loại ghế cấu hình.
         */
        get: operations["SeatTypesController_findMany"];
        put?: never;
        /**
         * Tạo loại ghế
         * @description Yêu cầu SEAT_TYPES_CREATE.
         */
        post: operations["SeatTypesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seat-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chi tiết loại ghế
         * @description Lấy loại ghế theo UUID.
         */
        get: operations["SeatTypesController_findById"];
        put?: never;
        post?: never;
        /**
         * Vô hiệu hóa loại ghế
         * @description Seat types không có deletedAt, endpoint chuyển status về INACTIVE.
         */
        delete: operations["SeatTypesController_delete"];
        options?: never;
        head?: never;
        /**
         * Cập nhật loại ghế
         * @description Yêu cầu SEAT_TYPES_UPDATE.
         */
        patch: operations["SeatTypesController_update"];
        trace?: never;
    };
    "/trains/{trainId}/carriages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh sách toa của tàu
         * @description Lấy danh sách toa chưa bị xóa mềm của một tàu.
         */
        get: operations["CarriagesController_findMany"];
        put?: never;
        /**
         * Tạo toa cho tàu
         * @description Tạo toa thuộc một tàu. trainId phải tồn tại và chưa bị xóa mềm.
         */
        post: operations["CarriagesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carriages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chi tiết toa
         * @description Lấy chi tiết toa kèm danh sách ghế.
         */
        get: operations["CarriagesController_findById"];
        put?: never;
        post?: never;
        /**
         * Xóa mềm toa
         * @description Không hard delete, chỉ cập nhật deletedAt.
         */
        delete: operations["CarriagesController_delete"];
        options?: never;
        head?: never;
        /**
         * Cập nhật toa
         * @description Cập nhật thông tin toa. Yêu cầu CARRIAGES_UPDATE.
         */
        patch: operations["CarriagesController_update"];
        trace?: never;
    };
    "/carriages/{carriageId}/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh sách ghế của toa
         * @description Lấy danh sách ghế chưa bị xóa mềm của một toa.
         */
        get: operations["SeatsController_findMany"];
        put?: never;
        /**
         * Tạo ghế trong toa
         * @description Tạo ghế thuộc toa. Toa phải tồn tại, chưa bị xóa mềm; loại ghế phải ACTIVE và allowedCarriageTypes phải chứa carriageType của toa.
         */
        post: operations["SeatsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seats/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chi tiết ghế
         * @description Lấy chi tiết ghế theo UUID.
         */
        get: operations["SeatsController_findById"];
        put?: never;
        post?: never;
        /**
         * Xóa mềm ghế
         * @description Không hard delete, chỉ cập nhật deletedAt.
         */
        delete: operations["SeatsController_delete"];
        options?: never;
        head?: never;
        /**
         * Cập nhật ghế
         * @description Cập nhật thông tin ghế. Nếu đổi seatTypeId thì loại ghế phải ACTIVE và phù hợp với carriageType của toa.
         */
        patch: operations["SeatsController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateUserDto: {
            /**
             * @description Email đăng nhập hoặc nhận vé
             * @example user@example.com
             */
            email?: string;
            /**
             * @description Số điện thoại đăng nhập hoặc nhận thông báo
             * @example 0901234567
             */
            phone?: string;
            /**
             * @description Mật khẩu đăng nhập. BE sẽ tự hash trước khi lưu.
             * @example Admin-sSjRqGa9JH-6#1
             */
            password: string;
            /**
             * @description Họ tên hiển thị
             * @example Nguyễn Văn A
             */
            fullName: string;
            /**
             * @description Loại người dùng
             * @example CUSTOMER
             * @enum {string}
             */
            userType: "CUSTOMER" | "STAFF" | "SYSTEM";
            /**
             * @description Trạng thái tài khoản
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE" | "LOCKED";
            /**
             * @description Danh sách ID vai trò gán cho người dùng
             * @example [
             *       1,
             *       2
             *     ]
             */
            roleIds?: number[];
        };
        UpdateUserDto: {
            /**
             * @description Email đăng nhập hoặc nhận vé
             * @example user@example.com
             */
            email?: string;
            /**
             * @description Số điện thoại đăng nhập hoặc nhận thông báo
             * @example 0901234567
             */
            phone?: string;
            /**
             * @description Mật khẩu đăng nhập. BE sẽ tự hash trước khi lưu.
             * @example Admin-sSjRqGa9JH-6#1
             */
            password?: string;
            /**
             * @description Họ tên hiển thị
             * @example Nguyễn Văn A
             */
            fullName?: string;
            /**
             * @description Loại người dùng
             * @example CUSTOMER
             * @enum {string}
             */
            userType?: "CUSTOMER" | "STAFF" | "SYSTEM";
            /**
             * @description Trạng thái tài khoản
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE" | "LOCKED";
            /**
             * @description Danh sách ID vai trò gán cho người dùng
             * @example [
             *       1,
             *       2
             *     ]
             */
            roleIds?: number[];
        };
        RegisterDto: {
            /**
             * @description Email đăng nhập. Bắt buộc nếu không truyền số điện thoại
             * @example customer@example.com
             */
            email?: string;
            /**
             * @description Số điện thoại đăng nhập. Bắt buộc nếu không truyền email
             * @example 0901234567
             */
            phone?: string;
            /**
             * @description Họ tên hiển thị của người dùng
             * @example Nguyễn Văn A
             */
            fullName: string;
            /**
             * @description Mật khẩu thô, API sẽ hash trước khi lưu
             * @example secret123
             */
            password: string;
        };
        LoginDto: {
            /**
             * @description Email hoặc số điện thoại dùng để đăng nhập
             * @example admin@traintickets.local
             */
            identifier: string;
            /**
             * @description Mật khẩu tài khoản
             * @example Admin-sSjRqGa9JH-6#1
             */
            password: string;
        };
        RefreshTokenDto: {
            /**
             * @description Refresh token còn hiệu lực để cấp cặp token mới
             * @example refresh-token-tu-api-login
             */
            refreshToken: string;
        };
        LogoutDto: {
            /**
             * @description Refresh token cần thu hồi
             * @example refresh-token-tu-api-login
             */
            refreshToken: string;
        };
        CreateRoleDto: {
            /**
             * @description Mã vai trò duy nhất, viết hoa, không dấu, không khoảng trắng
             * @example OPERATOR
             */
            code: string;
            /**
             * @description Tên hiển thị của vai trò
             * @example Nhân viên vận hành
             */
            name: string;
            /**
             * @description Mô tả vai trò
             * @example Có quyền quản lý dữ liệu vận hành cơ bản
             */
            description?: string;
            /**
             * @description Trạng thái vai trò
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
        };
        UpdateRoleDto: {
            /**
             * @description Mã vai trò duy nhất, viết hoa, không dấu, không khoảng trắng
             * @example OPERATOR
             */
            code?: string;
            /**
             * @description Tên hiển thị của vai trò
             * @example Nhân viên vận hành
             */
            name?: string;
            /**
             * @description Mô tả vai trò
             * @example Có quyền quản lý dữ liệu vận hành cơ bản
             */
            description?: string;
            /**
             * @description Trạng thái vai trò
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE";
        };
        SyncRolePermissionsDto: {
            /**
             * @description Danh sách mã quyền active sẽ được gán cho vai trò. API sẽ thay thế toàn bộ danh sách cũ.
             * @example [
             *       "ROLES_READ",
             *       "PERMISSIONS_READ",
             *       "STATIONS_READ"
             *     ]
             */
            permissionCodes: string[];
        };
        CreatePermissionDto: {
            /**
             * @description Mã quyền duy nhất dùng trong code và seed
             * @example STATIONS_CREATE
             */
            code: string;
            /**
             * @description Tên hiển thị của quyền
             * @example Tạo ga
             */
            name: string;
            /**
             * @description Mô tả quyền
             * @example Cho phép tạo ga tàu mới trong CMS
             */
            description?: string;
            /**
             * @description Module hoặc nhóm chức năng sở hữu quyền
             * @example stations
             */
            module: string;
            /**
             * @description Hành động nghiệp vụ của quyền
             * @example create
             */
            action: string;
            /**
             * @description HTTP method dùng để check quyền theo route runtime
             * @example POST
             */
            method?: string;
            /**
             * @description Path route dùng để check quyền runtime, dùng format của controller như /roles/:id
             * @example /stations
             */
            path?: string;
            /**
             * @description Trạng thái quyền
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
        };
        UpdatePermissionDto: {
            /**
             * @description Mã quyền duy nhất dùng trong code và seed
             * @example STATIONS_CREATE
             */
            code?: string;
            /**
             * @description Tên hiển thị của quyền
             * @example Tạo ga
             */
            name?: string;
            /**
             * @description Mô tả quyền
             * @example Cho phép tạo ga tàu mới trong CMS
             */
            description?: string;
            /**
             * @description Module hoặc nhóm chức năng sở hữu quyền
             * @example stations
             */
            module?: string;
            /**
             * @description Hành động nghiệp vụ của quyền
             * @example create
             */
            action?: string;
            /**
             * @description HTTP method dùng để check quyền theo route runtime
             * @example POST
             */
            method?: string;
            /**
             * @description Path route dùng để check quyền runtime, dùng format của controller như /roles/:id
             * @example /stations
             */
            path?: string;
            /**
             * @description Trạng thái quyền
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE";
        };
        CreateStationDto: {
            /**
             * @description Mã ga duy nhất, viết hoa, không dấu, không khoảng trắng
             * @example HAN
             */
            code: string;
            /**
             * @description Tên ga hiển thị cho khách hàng và nhân viên vận hành
             * @example Ga Hà Nội
             */
            name: string;
            /**
             * @description Slug URL-friendly duy nhất của ga
             * @example ga-ha-noi
             */
            slug: string;
            /**
             * @description Tỉnh hoặc thành phố của ga
             * @example Hà Nội
             */
            city?: string;
            /**
             * @description Địa chỉ chi tiết của ga
             * @example 120 Lê Duẩn, Hoàn Kiếm
             */
            address?: string;
            /**
             * @description Vĩ độ của ga, dùng cho bản đồ hoặc tính khoảng cách
             * @example 21.0245
             */
            latitude?: number;
            /**
             * @description Kinh độ của ga, dùng cho bản đồ hoặc tính khoảng cách
             * @example 105.8412
             */
            longitude?: number;
            /**
             * @description Múi giờ vận hành của ga
             * @default Asia/Ho_Chi_Minh
             * @example Asia/Ho_Chi_Minh
             */
            timezone: string;
            /**
             * @description Trạng thái ga. Ga INACTIVE không dùng để bán vé mới.
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
        };
        UpdateStationDto: {
            /**
             * @description Mã ga duy nhất, viết hoa, không dấu, không khoảng trắng
             * @example HAN
             */
            code?: string;
            /**
             * @description Tên ga hiển thị cho khách hàng và nhân viên vận hành
             * @example Ga Hà Nội
             */
            name?: string;
            /**
             * @description Slug URL-friendly duy nhất của ga
             * @example ga-ha-noi
             */
            slug?: string;
            /**
             * @description Tỉnh hoặc thành phố của ga
             * @example Hà Nội
             */
            city?: string;
            /**
             * @description Địa chỉ chi tiết của ga
             * @example 120 Lê Duẩn, Hoàn Kiếm
             */
            address?: string;
            /**
             * @description Vĩ độ của ga, dùng cho bản đồ hoặc tính khoảng cách
             * @example 21.0245
             */
            latitude?: number;
            /**
             * @description Kinh độ của ga, dùng cho bản đồ hoặc tính khoảng cách
             * @example 105.8412
             */
            longitude?: number;
            /**
             * @description Múi giờ vận hành của ga
             * @default Asia/Ho_Chi_Minh
             * @example Asia/Ho_Chi_Minh
             */
            timezone: string;
            /**
             * @description Trạng thái ga. Ga INACTIVE không dùng để bán vé mới.
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE";
        };
        RouteStopDto: {
            /**
             * @description UUID ga dừng trên tuyến
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            stationId: string;
            /**
             * @description Thứ tự ga dừng trên tuyến, bắt đầu từ 1
             * @example 1
             */
            stopOrder: number;
            /**
             * @description Khoảng cách từ ga đầu tuyến đến ga này, đơn vị km
             * @example 0
             */
            distanceFromStartKm: number;
            /**
             * @description Số phút mặc định từ ga đầu đến lúc tàu đến ga này
             * @example 360
             */
            defaultArrivalOffsetMinutes?: number;
            /**
             * @description Số phút mặc định từ ga đầu đến lúc tàu rời ga này
             * @example 370
             */
            defaultDepartureOffsetMinutes?: number;
        };
        CreateRouteDto: {
            /**
             * @description Mã tuyến duy nhất, viết hoa, không dấu, cho phép dấu gạch ngang
             * @example HN-DN
             */
            code: string;
            /**
             * @description Tên tuyến hiển thị cho nhân viên vận hành
             * @example Hà Nội - Đà Nẵng
             */
            name: string;
            /**
             * @description Mô tả tuyến cho vận hành hoặc SEO sau này
             * @example Tuyến Bắc Trung Bộ kết nối Hà Nội, Vinh và Đà Nẵng.
             */
            description?: string;
            /**
             * @description Trạng thái tuyến. Tuyến INACTIVE không dùng để mở bán mới.
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            /** @description Danh sách ga dừng. Một tuyến phải có ít nhất 2 ga. */
            stops: components["schemas"]["RouteStopDto"][];
        };
        UpdateRouteDto: {
            /**
             * @description Mã tuyến duy nhất, viết hoa, không dấu, cho phép dấu gạch ngang
             * @example HN-DN
             */
            code?: string;
            /**
             * @description Tên tuyến hiển thị cho nhân viên vận hành
             * @example Hà Nội - Đà Nẵng
             */
            name?: string;
            /**
             * @description Mô tả tuyến cho vận hành hoặc SEO sau này
             * @example Tuyến Bắc Trung Bộ kết nối Hà Nội, Vinh và Đà Nẵng.
             */
            description?: string;
            /**
             * @description Trạng thái tuyến. Tuyến INACTIVE không dùng để mở bán mới.
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE";
            /** @description Danh sách ga dừng. Một tuyến phải có ít nhất 2 ga. */
            stops?: components["schemas"]["RouteStopDto"][];
        };
        CreateTrainDto: {
            /**
             * @description Mã tàu duy nhất, viết hoa, không dấu, không khoảng trắng
             * @example SE1
             */
            code: string;
            /**
             * @description Tên tàu hiển thị cho vận hành
             * @example Tàu SE1
             */
            name: string;
            /**
             * @description Mô tả hoặc ghi chú cấu hình tàu
             * @example Tàu Thống Nhất chạy tuyến Bắc Nam.
             */
            description?: string;
            /**
             * @description Trạng thái tàu
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "MAINTENANCE" | "INACTIVE";
        };
        UpdateTrainDto: {
            /**
             * @description Mã tàu duy nhất, viết hoa, không dấu, không khoảng trắng
             * @example SE1
             */
            code?: string;
            /**
             * @description Tên tàu hiển thị cho vận hành
             * @example Tàu SE1
             */
            name?: string;
            /**
             * @description Mô tả hoặc ghi chú cấu hình tàu
             * @example Tàu Thống Nhất chạy tuyến Bắc Nam.
             */
            description?: string;
            /**
             * @description Trạng thái tàu
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "MAINTENANCE" | "INACTIVE";
        };
        CreateSeatTypeDto: {
            /**
             * @description Mã loại ghế viết hoa, không dấu, cho phép dấu gạch dưới
             * @example SOFT_SEAT
             */
            code: string;
            /**
             * @description Tên loại ghế hiển thị
             * @example Ghế mềm
             */
            name: string;
            /**
             * @description Mô tả tiện ích hoặc điều kiện của loại ghế
             * @example Ghế mềm điều hòa.
             */
            description?: string;
            /**
             * @description Hệ số nhân giá so với giá cơ bản, phải lớn hơn 0
             * @example 1.2
             */
            baseMultiplier: number;
            /**
             * @description Danh sách loại toa được phép dùng loại ghế này. FE dùng field này để lọc dropdown loại ghế theo toa.
             * @example [
             *       "SEAT"
             *     ]
             */
            allowedCarriageTypes: ("SEAT" | "SLEEPER" | "VIP")[];
            /**
             * @description Trạng thái loại ghế
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
        };
        UpdateSeatTypeDto: {
            /**
             * @description Mã loại ghế viết hoa, không dấu, cho phép dấu gạch dưới
             * @example SOFT_SEAT
             */
            code?: string;
            /**
             * @description Tên loại ghế hiển thị
             * @example Ghế mềm
             */
            name?: string;
            /**
             * @description Mô tả tiện ích hoặc điều kiện của loại ghế
             * @example Ghế mềm điều hòa.
             */
            description?: string;
            /**
             * @description Hệ số nhân giá so với giá cơ bản, phải lớn hơn 0
             * @example 1.2
             */
            baseMultiplier?: number;
            /**
             * @description Danh sách loại toa được phép dùng loại ghế này. FE dùng field này để lọc dropdown loại ghế theo toa.
             * @example [
             *       "SEAT"
             *     ]
             */
            allowedCarriageTypes?: ("SEAT" | "SLEEPER" | "VIP")[];
            /**
             * @description Trạng thái loại ghế
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE";
        };
        CreateCarriageDto: {
            /**
             * @description Số thứ tự toa trong cùng tàu, không được trùng
             * @example 1
             */
            carriageNumber: number;
            /**
             * @description Tên toa hiển thị
             * @example Toa 1 ghế ngồi
             */
            name: string;
            /**
             * @description Loại toa chính thức. SEAT: toa ghế ngồi, SLEEPER: toa giường nằm, VIP: toa VIP.
             * @example SEAT
             * @enum {string}
             */
            carriageType: "SEAT" | "SLEEPER" | "VIP";
            /**
             * @description JSON layout để client render sơ đồ ghế
             * @example {
             *       "rows": 10,
             *       "columns": 4,
             *       "aisleAfterColumn": 2
             *     }
             */
            seatMapLayout?: Record<string, never>;
            /**
             * @description Trạng thái toa
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "MAINTENANCE" | "INACTIVE";
        };
        UpdateCarriageDto: {
            /**
             * @description Số thứ tự toa trong cùng tàu, không được trùng
             * @example 1
             */
            carriageNumber?: number;
            /**
             * @description Tên toa hiển thị
             * @example Toa 1 ghế ngồi
             */
            name?: string;
            /**
             * @description Loại toa chính thức. SEAT: toa ghế ngồi, SLEEPER: toa giường nằm, VIP: toa VIP.
             * @example SEAT
             * @enum {string}
             */
            carriageType?: "SEAT" | "SLEEPER" | "VIP";
            /**
             * @description JSON layout để client render sơ đồ ghế
             * @example {
             *       "rows": 10,
             *       "columns": 4,
             *       "aisleAfterColumn": 2
             *     }
             */
            seatMapLayout?: Record<string, never>;
            /**
             * @description Trạng thái toa
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "MAINTENANCE" | "INACTIVE";
        };
        CreateSeatDto: {
            /**
             * @description UUID loại ghế, phải tồn tại và đang ACTIVE
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            seatTypeId: string;
            /**
             * @description Số ghế trong toa, không được trùng trong cùng toa
             * @example A1
             */
            seatNumber: string;
            /**
             * @description Dòng hiển thị trên sơ đồ ghế
             * @example 1
             */
            rowNumber?: number;
            /**
             * @description Cột hiển thị trên sơ đồ ghế
             * @example 2
             */
            columnNumber?: number;
            /**
             * @description Tầng giường nằm nếu có
             * @example 1
             */
            floorNumber?: number;
            /**
             * @description Trạng thái ghế
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "BROKEN" | "INACTIVE";
        };
        UpdateSeatDto: {
            /**
             * @description UUID loại ghế, phải tồn tại và đang ACTIVE
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            seatTypeId?: string;
            /**
             * @description Số ghế trong toa, không được trùng trong cùng toa
             * @example A1
             */
            seatNumber?: string;
            /**
             * @description Dòng hiển thị trên sơ đồ ghế
             * @example 1
             */
            rowNumber?: number;
            /**
             * @description Cột hiển thị trên sơ đồ ghế
             * @example 2
             */
            columnNumber?: number;
            /**
             * @description Tầng giường nằm nếu có
             * @example 1
             */
            floorNumber?: number;
            /**
             * @description Trạng thái ghế
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "BROKEN" | "INACTIVE";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description API hoạt động và database kết nối được.
             *
             *     The Health Check is successful
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
    UsersController_findMany: {
        parameters: {
            query?: {
                /** @description Trang hiện tại */
                page?: number;
                /** @description Số bản ghi mỗi trang, tối đa 100 */
                limit?: number;
                /** @description Tìm theo họ tên, email hoặc số điện thoại */
                search?: string;
                /** @description Lọc theo loại người dùng */
                userType?: "CUSTOMER" | "STAFF" | "SYSTEM";
                /** @description Lọc theo trạng thái tài khoản */
                status?: "ACTIVE" | "INACTIVE" | "LOCKED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Danh sách người dùng. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission USERS_READ. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description Người dùng đã được tạo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission USERS_CREATE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID người dùng */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chi tiết người dùng. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission USERS_READ. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID người dùng */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Người dùng đã bị xóa mềm. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission USERS_DELETE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID người dùng */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            /** @description Người dùng đã được cập nhật. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission USERS_UPDATE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description Đăng ký thành công, trả token và thông tin user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu email/số điện thoại hoặc email/số điện thoại đã tồn tại. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Đăng nhập thành công, trả access token + refresh token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thông tin đăng nhập không hợp lệ. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            /** @description Refresh token hợp lệ, trả token mới. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refresh token không hợp lệ hoặc đã hết hạn. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutDto"];
            };
        };
        responses: {
            /** @description Đăng xuất thành công. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thông tin user hiện tại. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu token hoặc token không hợp lệ. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_findMany: {
        parameters: {
            query?: {
                /** @description Tìm theo code hoặc tên vai trò */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Danh sách vai trò. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleDto"];
            };
        };
        responses: {
            /** @description Vai trò đã được tạo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission ROLES_CREATE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID vai trò */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chi tiết vai trò. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID vai trò */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vai trò đã bị vô hiệu hóa. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID vai trò */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleDto"];
            };
        };
        responses: {
            /** @description Vai trò đã được cập nhật. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_syncPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID vai trò */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRolePermissionsDto"];
            };
        };
        responses: {
            /** @description Danh sách quyền của vai trò đã được đồng bộ. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PermissionsController_findMany: {
        parameters: {
            query?: {
                /** @description Tìm theo code, tên quyền hoặc module */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Danh sách quyền. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PermissionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePermissionDto"];
            };
        };
        responses: {
            /** @description Quyền đã được tạo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission PERMISSIONS_CREATE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PermissionsController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID quyền */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chi tiết quyền. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PermissionsController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID quyền */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quyền đã bị vô hiệu hóa. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PermissionsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID quyền */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePermissionDto"];
            };
        };
        responses: {
            /** @description Quyền đã được cập nhật. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StationsController_findMany: {
        parameters: {
            query?: {
                /** @description Trang hiện tại */
                page?: number;
                /** @description Số bản ghi mỗi trang, tối đa 100 */
                limit?: number;
                /** @description Tìm theo tên ga hoặc mã ga */
                search?: string;
                /** @description Lọc theo tỉnh/thành phố */
                city?: string;
                /** @description Lọc theo trạng thái ACTIVE hoặc INACTIVE */
                status?: "ACTIVE" | "INACTIVE";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Danh sách ga. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission STATIONS_READ. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StationsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStationDto"];
            };
        };
        responses: {
            /** @description Ga đã được tạo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission STATIONS_CREATE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StationsController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID ga */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chi tiết ga. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission STATIONS_READ. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StationsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID ga */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ga đã được xóa mềm. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission STATIONS_DELETE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StationsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID ga */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStationDto"];
            };
        };
        responses: {
            /** @description Ga đã được cập nhật. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission STATIONS_UPDATE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutesController_findMany: {
        parameters: {
            query?: {
                /** @description Trang hiện tại */
                page?: number;
                /** @description Số bản ghi mỗi trang, tối đa 100 */
                limit?: number;
                /** @description Tìm theo tên tuyến hoặc mã tuyến */
                search?: string;
                /** @description Lọc theo trạng thái ACTIVE hoặc INACTIVE */
                status?: "ACTIVE" | "INACTIVE";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Danh sách tuyến. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission ROUTES_READ. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRouteDto"];
            };
        };
        responses: {
            /** @description Tuyến đã được tạo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission ROUTES_CREATE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutesController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID tuyến */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chi tiết tuyến. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission ROUTES_READ. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutesController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID tuyến */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tuyến đã được xóa mềm. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission ROUTES_DELETE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID tuyến */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRouteDto"];
            };
        };
        responses: {
            /** @description Tuyến đã được cập nhật. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission ROUTES_UPDATE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrainsController_findMany: {
        parameters: {
            query?: {
                /** @description Trang hiện tại */
                page?: number;
                /** @description Số bản ghi mỗi trang */
                limit?: number;
                /** @description Tìm theo mã tàu hoặc tên tàu */
                search?: string;
                /** @description Lọc theo trạng thái tàu */
                status?: "ACTIVE" | "MAINTENANCE" | "INACTIVE";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Danh sách tàu. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission TRAINS_READ. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrainsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTrainDto"];
            };
        };
        responses: {
            /** @description Tàu đã được tạo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission TRAINS_CREATE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrainsController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID tàu */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chi tiết tàu. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission TRAINS_READ. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrainsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID tàu */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tàu đã được xóa mềm. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission TRAINS_DELETE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrainsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID tàu */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTrainDto"];
            };
        };
        responses: {
            /** @description Tàu đã được cập nhật. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission TRAINS_UPDATE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SeatTypesController_findMany: {
        parameters: {
            query?: {
                /** @description Trang hiện tại */
                page?: number;
                /** @description Số bản ghi mỗi trang */
                limit?: number;
                /** @description Tìm theo mã hoặc tên loại ghế */
                search?: string;
                /** @description Lọc theo trạng thái loại ghế */
                status?: "ACTIVE" | "INACTIVE";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Danh sách loại ghế. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission SEAT_TYPES_READ. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SeatTypesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSeatTypeDto"];
            };
        };
        responses: {
            /** @description Loại ghế đã được tạo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission SEAT_TYPES_CREATE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SeatTypesController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID loại ghế */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chi tiết loại ghế. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission SEAT_TYPES_READ. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SeatTypesController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID loại ghế */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Loại ghế đã được vô hiệu hóa. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission SEAT_TYPES_DELETE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SeatTypesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID loại ghế */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSeatTypeDto"];
            };
        };
        responses: {
            /** @description Loại ghế đã được cập nhật. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission SEAT_TYPES_UPDATE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CarriagesController_findMany: {
        parameters: {
            query?: {
                /** @description Trang hiện tại */
                page?: number;
                /** @description Số bản ghi mỗi trang */
                limit?: number;
                /** @description Tìm theo tên toa hoặc loại toa */
                search?: string;
                /** @description Lọc theo trạng thái toa */
                status?: "ACTIVE" | "MAINTENANCE" | "INACTIVE";
            };
            header?: never;
            path: {
                /** @description UUID tàu */
                trainId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Danh sách toa. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission CARRIAGES_READ. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CarriagesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID tàu */
                trainId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCarriageDto"];
            };
        };
        responses: {
            /** @description Toa đã được tạo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission CARRIAGES_CREATE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CarriagesController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID toa */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chi tiết toa. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission CARRIAGES_READ_DETAIL. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CarriagesController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID toa */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Toa đã được xóa mềm. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission CARRIAGES_DELETE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CarriagesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID toa */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCarriageDto"];
            };
        };
        responses: {
            /** @description Toa đã được cập nhật. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission CARRIAGES_UPDATE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SeatsController_findMany: {
        parameters: {
            query?: {
                /** @description Trang hiện tại */
                page?: number;
                /** @description Số bản ghi mỗi trang */
                limit?: number;
                /** @description Tìm theo số ghế */
                search?: string;
                /** @description Lọc theo trạng thái ghế */
                status?: "ACTIVE" | "BROKEN" | "INACTIVE";
            };
            header?: never;
            path: {
                /** @description UUID toa */
                carriageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Danh sách ghế. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission SEATS_READ. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SeatsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID toa */
                carriageId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSeatDto"];
            };
        };
        responses: {
            /** @description Ghế đã được tạo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dữ liệu không hợp lệ, ví dụ seatType không phù hợp với carriageType của toa. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission SEATS_CREATE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SeatsController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID ghế */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chi tiết ghế. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission SEATS_READ_DETAIL. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SeatsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID ghế */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ghế đã được xóa mềm. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission SEATS_DELETE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SeatsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID ghế */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSeatDto"];
            };
        };
        responses: {
            /** @description Ghế đã được cập nhật. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dữ liệu không hợp lệ, ví dụ seatType không phù hợp với carriageType của toa. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thiếu hoặc sai access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User không có permission SEATS_UPDATE. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
